//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DentalSoftware {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.8.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Provider = Microsoft.ACE.OLEDB.12.0; Data Source = |DataDirectory|\\database.accdb" +
            ";")]
        public string CONNECTION_STRING {
            get {
                return ((string)(this["CONNECTION_STRING"]));
            }
            set {
                this["CONNECTION_STRING"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("08:00:00")]
        public global::System.TimeSpan APPOINTMENT_START_TIME {
            get {
                return ((global::System.TimeSpan)(this["APPOINTMENT_START_TIME"]));
            }
            set {
                this["APPOINTMENT_START_TIME"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("18:30:00")]
        public global::System.TimeSpan APPOINTMENT_END_TIME {
            get {
                return ((global::System.TimeSpan)(this["APPOINTMENT_END_TIME"]));
            }
            set {
                this["APPOINTMENT_END_TIME"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:15:00")]
        public global::System.TimeSpan APPOINTMENT_DURATION {
            get {
                return ((global::System.TimeSpan)(this["APPOINTMENT_DURATION"]));
            }
            set {
                this["APPOINTMENT_DURATION"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color APPOINTMENT_FAST_PAINT_COLOR_1 {
            get {
                return ((global::System.Drawing.Color)(this["APPOINTMENT_FAST_PAINT_COLOR_1"]));
            }
            set {
                this["APPOINTMENT_FAST_PAINT_COLOR_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color APPOINTMENT_FAST_PAINT_COLOR_2 {
            get {
                return ((global::System.Drawing.Color)(this["APPOINTMENT_FAST_PAINT_COLOR_2"]));
            }
            set {
                this["APPOINTMENT_FAST_PAINT_COLOR_2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color APPOINTMENT_FAST_PAINT_COLOR_3 {
            get {
                return ((global::System.Drawing.Color)(this["APPOINTMENT_FAST_PAINT_COLOR_3"]));
            }
            set {
                this["APPOINTMENT_FAST_PAINT_COLOR_3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color APPOINTMENT_FAST_PAINT_COLOR_4 {
            get {
                return ((global::System.Drawing.Color)(this["APPOINTMENT_FAST_PAINT_COLOR_4"]));
            }
            set {
                this["APPOINTMENT_FAST_PAINT_COLOR_4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color APPOINTMENT_FAST_PAINT_COLOR_5 {
            get {
                return ((global::System.Drawing.Color)(this["APPOINTMENT_FAST_PAINT_COLOR_5"]));
            }
            set {
                this["APPOINTMENT_FAST_PAINT_COLOR_5"] = value;
            }
        }
    }
}
